;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Test
DestinationPath=Content/Localization/Test
ManifestName=Test.manifest
ArchiveName=Test.archive
CulturesToGenerate=en
CulturesToGenerate=zh

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=Test.csv

