;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Test
DestinationPath=Content/Localization/Test
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=zh
ManifestName=Test.manifest
ArchiveName=Test.archive
DialogueScriptName=TestDialogue.csv

[GatherTextStep0]
CommandletClass=ExportDialogueScript

