;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Test
DestinationPath=Content/Localization/Test
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=zh
ManifestName=Test.manifest
ArchiveName=Test.archive
PortableObjectName=Test.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bExportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Unreal
ShouldPersistCommentsOnExport=false
ShouldAddSourceLocationsAsComments=true

